# Generated by Django 5.0.2 on 2024-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='review',
            field=models.CharField(max_length=50000000),
        ),
    ]
