# Generated by Django 5.0.2 on 2024-02-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_data_price_alter_data_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
