# Generated by Django 5.0.2 on 2024-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_wordcloud_remove_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='price',
        ),
        migrations.AddField(
            model_name='data',
            name='hotel_location',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
