# Generated by Django 5.0.2 on 2024-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_remove_data_price_data_hotel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='rating',
            field=models.FloatField(),
        ),
    ]
