# Generated by Django 5.0.2 on 2024-02-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_alter_data_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloud',
            name='caption',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
